apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  ports:
  - name: http 
    port: 80 
    protocol: TCP
    targetPort: 80
    nodePort: OVERLAY 
  selector:
    app: nginx
  type: NodePort
