apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

patches:
- path: ./patch-svc.yaml

configMapGenerator:
- name: cm-index
  files:
  - index.html
  options:
    disableNameSuffixHash: false
