apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sampleapp 
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://kubernetes.default.svc
      - cluster: prod
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{.cluster}}-sampleapp'
    spec:
      project: sampleapp-prj 
      source:
        repoURL: https://github.com/roberrodriguez/demo-gitops.git 
        targetRevision: HEAD
        path: sampleapp/{{.cluster}}
      destination:
        server: '{{.url}}'
        namespace: '{{.cluster}}-sampleapp'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true

