apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: argo-svc
  name: argo-svc
spec:
  ports:
  - name: argo-http 
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30080 
  selector:
    app.kubernetes.io/name: argocd-server 
  type: NodePort
status:
  loadBalancer: {}
