apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
spec:
  ports:
  - name: 8081-80
    port: 80 
    protocol: TCP
    targetPort: 80
    nodePort: 30001
  selector:
    app: nginx
  type: NodePort
status:
  loadBalancer: {}
